# Generated by Django 5.0.14 on 2026-07-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('mention', 'Mention'), ('reply', 'Reply'), ('upvote', 'Upvote')], default='mention', max_length=10),
        ),
    ]
