# Generated by Django 5.0.14 on 2026-07-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
