# Generated by Django 5.0.14 on 2026-07-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
