# Generated by Django 5.0.14 on 2026-07-14 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_postrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='posts.comment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
