from django.urls import path

from . import views

urlpatterns = [
    path("", views.GamesHubView.as_view(), name="games-hub"),
    path("leaderboard/", views.LeaderboardView.as_view(), name="games-leaderboard"),
    path("match/<uuid:pk>/status/", views.MatchStatusView.as_view(), name="match-status"),
    path("your-turn-count/", views.YourTurnCountView.as_view(), name="your-turn-count"),
    path("ttt/challenge/<str:username>/", views.TicTacToeChallengeView.as_view(), name="ttt-challenge"),
    path("ttt/<uuid:pk>/", views.TicTacToeMatchView.as_view(), name="ttt-match"),
    path("ttt/<uuid:pk>/move/", views.TicTacToeMoveView.as_view(), name="ttt-move"),
    path("rps/challenge/<str:username>/", views.RockPaperScissorsChallengeView.as_view(), name="rps-challenge"),
    path("rps/<uuid:pk>/", views.RockPaperScissorsMatchView.as_view(), name="rps-match"),
    path("rps/<uuid:pk>/move/", views.RockPaperScissorsMoveView.as_view(), name="rps-move"),
    path("connect4/challenge/<str:username>/", views.ConnectFourChallengeView.as_view(), name="connect4-challenge"),
    path("connect4/<uuid:pk>/", views.ConnectFourMatchView.as_view(), name="connect4-match"),
    path("connect4/<uuid:pk>/move/", views.ConnectFourMoveView.as_view(), name="connect4-move"),
    path("checkers/challenge/<str:username>/", views.CheckersChallengeView.as_view(), name="checkers-challenge"),
    path("checkers/<uuid:pk>/", views.CheckersMatchView.as_view(), name="checkers-match"),
    path("checkers/<uuid:pk>/move/", views.CheckersMoveView.as_view(), name="checkers-move"),
    path("othello/challenge/<str:username>/", views.OthelloChallengeView.as_view(), name="othello-challenge"),
    path("othello/<uuid:pk>/", views.OthelloMatchView.as_view(), name="othello-match"),
    path("othello/<uuid:pk>/move/", views.OthelloMoveView.as_view(), name="othello-move"),
    path("hangman/new/", views.HangmanNewView.as_view(), name="hangman-new"),
    path("hangman/", views.HangmanPlayView.as_view(), name="hangman-play"),
    path("hangman/guess/", views.HangmanGuessView.as_view(), name="hangman-guess"),
    path("2048/", views.Game2048View.as_view(), name="2048-play"),
    path("2048/finish/", views.Game2048FinishView.as_view(), name="2048-finish"),
    path("snake/", views.SnakeView.as_view(), name="snake-play"),
    path("snake/finish/", views.SnakeFinishView.as_view(), name="snake-finish"),
    path("doodle/", views.DoodleJumpView.as_view(), name="doodle-play"),
    path("doodle/finish/", views.DoodleJumpFinishView.as_view(), name="doodle-finish"),
    path("wordle/new/", views.WordleNewView.as_view(), name="wordle-new"),
    path("wordle/", views.WordlePlayView.as_view(), name="wordle-play"),
    path("wordle/guess/", views.WordleGuessView.as_view(), name="wordle-guess"),
]
