from django.urls import path

from . import views

urlpatterns = [
    path("", views.GamesHubView.as_view(), name="games-hub"),
    path("leaderboard/", views.LeaderboardView.as_view(), name="games-leaderboard"),
    path("match/<uuid:pk>/status/", views.MatchStatusView.as_view(), name="match-status"),
    path("your-turn-count/", views.YourTurnCountView.as_view(), name="your-turn-count"),
    path("ttt/challenge/<str:username>/", views.TicTacToeChallengeView.as_view(), name="ttt-challenge"),
    path("ttt/<uuid:pk>/", views.TicTacToeMatchView.as_view(), name="ttt-match"),
    path("ttt/<uuid:pk>/move/", views.TicTacToeMoveView.as_view(), name="ttt-move"),
    path("rps/challenge/<str:username>/", views.RockPaperScissorsChallengeView.as_view(), name="rps-challenge"),
    path("rps/<uuid:pk>/", views.RockPaperScissorsMatchView.as_view(), name="rps-match"),
    path("rps/<uuid:pk>/move/", views.RockPaperScissorsMoveView.as_view(), name="rps-move"),
    path("connect4/challenge/<str:username>/", views.ConnectFourChallengeView.as_view(), name="connect4-challenge"),
    path("connect4/<uuid:pk>/", views.ConnectFourMatchView.as_view(), name="connect4-match"),
    path("connect4/<uuid:pk>/move/", views.ConnectFourMoveView.as_view(), name="connect4-move"),
    path("checkers/challenge/<str:username>/", views.CheckersChallengeView.as_view(), name="checkers-challenge"),
    path("checkers/<uuid:pk>/", views.CheckersMatchView.as_view(), name="checkers-match"),
    path("checkers/<uuid:pk>/move/", views.CheckersMoveView.as_view(), name="checkers-move"),
    path("othello/challenge/<str:username>/", views.OthelloChallengeView.as_view(), name="othello-challenge"),
    path("othello/<uuid:pk>/", views.OthelloMatchView.as_view(), name="othello-match"),
    path("othello/<uuid:pk>/move/", views.OthelloMoveView.as_view(), name="othello-move"),
    path("nim/challenge/<str:username>/", views.NimChallengeView.as_view(), name="nim-challenge"),
    path("nim/<uuid:pk>/", views.NimMatchView.as_view(), name="nim-match"),
    path("nim/<uuid:pk>/move/", views.NimMoveView.as_view(), name="nim-move"),
    path(
        "battleship/challenge/<str:username>/",
        views.BattleshipChallengeView.as_view(),
        name="battleship-challenge",
    ),
    path("battleship/<uuid:pk>/", views.BattleshipMatchView.as_view(), name="battleship-match"),
    path("battleship/<uuid:pk>/place/", views.BattleshipPlaceView.as_view(), name="battleship-place"),
    path("battleship/<uuid:pk>/move/", views.BattleshipMoveView.as_view(), name="battleship-move"),
    path(
        "stratego/challenge/<str:username>/",
        views.StrategoChallengeView.as_view(),
        name="stratego-challenge",
    ),
    path("stratego/<uuid:pk>/", views.StrategoMatchView.as_view(), name="stratego-match"),
    path("stratego/<uuid:pk>/place/", views.StrategoPlaceView.as_view(), name="stratego-place"),
    path("stratego/<uuid:pk>/move/", views.StrategoMoveView.as_view(), name="stratego-move"),
    path(
        "morris/challenge/<str:username>/",
        views.NineMensMorrisChallengeView.as_view(),
        name="morris-challenge",
    ),
    path("morris/<uuid:pk>/", views.NineMensMorrisMatchView.as_view(), name="morris-match"),
    path("morris/<uuid:pk>/move/", views.NineMensMorrisMoveView.as_view(), name="morris-move"),
    path(
        "backgammon/challenge/<str:username>/",
        views.BackgammonChallengeView.as_view(),
        name="backgammon-challenge",
    ),
    path("backgammon/<uuid:pk>/", views.BackgammonMatchView.as_view(), name="backgammon-match"),
    path("backgammon/<uuid:pk>/move/", views.BackgammonMoveView.as_view(), name="backgammon-move"),
    path("hangman/new/", views.HangmanNewView.as_view(), name="hangman-new"),
    path("hangman/", views.HangmanPlayView.as_view(), name="hangman-play"),
    path("hangman/guess/", views.HangmanGuessView.as_view(), name="hangman-guess"),
    path("2048/", views.Game2048View.as_view(), name="2048-play"),
    path("2048/finish/", views.Game2048FinishView.as_view(), name="2048-finish"),
    path("snake/", views.SnakeView.as_view(), name="snake-play"),
    path("snake/finish/", views.SnakeFinishView.as_view(), name="snake-finish"),
    path("doodle/", views.DoodleJumpView.as_view(), name="doodle-play"),
    path("doodle/finish/", views.DoodleJumpFinishView.as_view(), name="doodle-finish"),
    path("flappy/", views.FlappyBirdView.as_view(), name="flappy-play"),
    path("flappy/finish/", views.FlappyBirdFinishView.as_view(), name="flappy-finish"),
    path("tetris/", views.TetrisView.as_view(), name="tetris-play"),
    path("tetris/finish/", views.TetrisFinishView.as_view(), name="tetris-finish"),
    path("wordle/new/", views.WordleNewView.as_view(), name="wordle-new"),
    path("wordle/", views.WordlePlayView.as_view(), name="wordle-play"),
    path("wordle/guess/", views.WordleGuessView.as_view(), name="wordle-guess"),
    path("mastermind/new/", views.MastermindNewView.as_view(), name="mastermind-new"),
    path("mastermind/", views.MastermindPlayView.as_view(), name="mastermind-play"),
    path("mastermind/guess/", views.MastermindGuessView.as_view(), name="mastermind-guess"),
]
