# Generated by Django 5.0.14 on 2026-07-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mute_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_on_mentions',
            field=models.BooleanField(default=True, verbose_name="Notify me when I'm mentioned"),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_on_replies',
            field=models.BooleanField(default=True, verbose_name='Notify me on replies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_on_upvotes',
            field=models.BooleanField(default=True, verbose_name='Notify me on upvotes'),
        ),
    ]
