# Generated by Django 5.0.14 on 2026-07-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_notify_on_reposts'),
        ('posts', '0018_comment_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pinned_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.post'),
        ),
    ]
