# Generated by Django 5.0.14 on 2026-07-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game',
            field=models.CharField(choices=[('ttt', 'Tic-Tac-Toe'), ('rps', 'Rock-Paper-Scissors'), ('connect4', 'Connect Four'), ('checkers', 'Checkers'), ('othello', 'Othello'), ('nim', 'Nim')], max_length=8),
        ),
    ]
