# Generated by Django 5.0.14 on 2026-07-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_match_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleplayerresult',
            name='game',
            field=models.CharField(choices=[('hangman', 'Word Guess'), ('2048', '2048'), ('snake', 'Snake'), ('doodle', 'Doodle Jump'), ('wordle', 'Wordle'), ('mmind', 'Mastermind')], max_length=8),
        ),
    ]
