# Generated by Django 5.0.14 on 2026-07-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_match_game_alter_singleplayerresult_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game',
            field=models.CharField(choices=[('ttt', 'Tic-Tac-Toe'), ('rps', 'Rock-Paper-Scissors'), ('connect4', 'Connect Four'), ('checkers', 'Checkers'), ('othello', 'Othello')], max_length=8),
        ),
        migrations.AlterField(
            model_name='singleplayerresult',
            name='game',
            field=models.CharField(choices=[('hangman', 'Word Guess'), ('2048', '2048'), ('snake', 'Snake'), ('doodle', 'Doodle Jump'), ('wordle', 'Wordle')], max_length=8),
        ),
    ]
