# Generated by Django 5.0.14 on 2026-07-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_match_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game',
            field=models.CharField(choices=[('ttt', 'Tic-Tac-Toe'), ('rps', 'Rock-Paper-Scissors'), ('connect4', 'Connect Four'), ('checkers', 'Checkers'), ('othello', 'Othello'), ('nim', 'Nim'), ('battle', 'Battleship'), ('stratego', 'Stratego')], max_length=8),
        ),
    ]
